/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.user.training.vass.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Training service. Represents a row in the &quot;TRAINING_Training&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.user.training.vass.model.impl.TrainingModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.user.training.vass.model.impl.TrainingImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Training
 * @generated
 */
@ProviderType
public interface TrainingModel extends BaseModel<Training> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a training model instance should use the {@link Training} interface instead.
	 */

	/**
	 * Returns the primary key of this training.
	 *
	 * @return the primary key of this training
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this training.
	 *
	 * @param primaryKey the primary key of this training
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this training.
	 *
	 * @return the uuid of this training
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this training.
	 *
	 * @param uuid the uuid of this training
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the training ID of this training.
	 *
	 * @return the training ID of this training
	 */
	public long getTrainingId();

	/**
	 * Sets the training ID of this training.
	 *
	 * @param trainingId the training ID of this training
	 */
	public void setTrainingId(long trainingId);

	/**
	 * Returns the user name of this training.
	 *
	 * @return the user name of this training
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this training.
	 *
	 * @param userName the user name of this training
	 */
	public void setUserName(String userName);

	/**
	 * Returns the email of this training.
	 *
	 * @return the email of this training
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this training.
	 *
	 * @param email the email of this training
	 */
	public void setEmail(String email);

	@Override
	public Training cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}