/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.user.training.vass.model.impl;

import com.user.training.vass.model.Training;
import com.user.training.vass.service.TrainingLocalServiceUtil;

/**
 * The extended model base implementation for the Training service. Represents a row in the &quot;TRAINING_Training&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrainingImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrainingImpl
 * @see Training
 * @generated
 */
public abstract class TrainingBaseImpl
	extends TrainingModelImpl implements Training {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a training model instance should use the <code>Training</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TrainingLocalServiceUtil.addTraining(this);
		}
		else {
			TrainingLocalServiceUtil.updateTraining(this);
		}
	}

}